version: '3'
services:
  inventory:
    build: /inventoryBackend/
    ports:
      - "8080:5000"

  shopping:
    build: /shoppingBackend/
    ports:
      - "8081:5001"

  androidtest:
    build:
      context: ./Frontend/
      dockerfile: ./Frontend/dockerfile
    depends_on:
      - inventory
      - shopping
    environment:
      - INVENTORY_URL=http://inventory:5000
      - SHOPPING_URL=http://shopping:5001
