name: Linter and Unit Tests

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker
      run: |
        docker build -t mybackend1 ./Backend/inventoryBackend
        docker build -t mybackend2 ./Backend/shoppingBackend
        docker run -d --name mybackend1 mybackend1
        docker run -d --name mybackend2 mybackend2

    - name: Run Unit Tests in Docker
      run: |
        docker exec -i mybackend1 pip install pytest
        docker exec -i mybackend2 pip install pytest
        docker exec -i mybackend1 pytest
        docker exec -i mybackend2 pytest

  android-test:
    name: Android Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t androidtest ./Frontend -f ./Frontend/dockerfile
    - name: Run tests in Docker
      run: |
        docker run --name androidtestcontainer androidtest
