name: Android CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Install Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
        unzip commandlinetools-linux-7302050_latest.zip -d $HOME/sdk
        echo "y" | $HOME/sdk/cmdline-tools/bin/sdkmanager "platforms;android-29" "build-tools;29.0.2" "system-images;android-29;default;x86"
        echo "no" | $HOME/sdk/cmdline-tools/bin/avdmanager create avd -n test -k "system-images;android-29;default;x86"
        
    - name: Start Emulator
      run: |
        $HOME/sdk/emulator/emulator -avd test -no-audio -no-window &
        $HOME/sdk/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
      
    - name: Run Tests
      run: |
        chmod +x ./gradlew
        ./gradlew connectedCheck


