name: Linter and Unit Tests

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker
      run: |
        docker build -t mybackend ./Backend/inventoryBackend
        docker run -d --name mybackend mybackend

    - name: Run Unit Tests in Docker
      run: |
        docker exec -i mybackend pip install pytest
        docker exec -i mybackend pytest

  android-test:
    name: Android Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t androidtest ./Frontend -f ./Frontend/Dockerfile
    - name: Run tests in Docker
      run: |
        docker run --name androidtestcontainer androidtest
