name: Android CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: '29'
        sdk-build-tools: '29.0.2'

    - name: Create AVD
      run: echo "no" | $ANDROID_HOME/cmdline-tools/bin/avdmanager create avd -n test -k "system-images;android-29;default;x86"
        
    - name: Start Emulator
      run: |
        $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
        $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
      
    - name: Run Tests
      run: |
        chmod +x ./gradlew
        ./gradlew connectedCheck


            
      